import type { RcmState } from "@/lib/rcm/types";

export const STORAGE_KEY = "alignment-rcm-demo-v1";

export function createSeedState(): RcmState {
  return {
    practice: {
      legalName: "The Alignment Clinic",
      physicianName: "Elvis Francois, MD",
      npi: "1999999984",
      taxId: "00-0000000",
      taxonomy: "207X00000X",
      phone: "(404) 555-0148",
      address: "Atlanta, GA",
      posCode: "11",
    },
    patients: [
      {
        id: "p1",
        firstName: "Avery",
        lastName: "Chen",
        dateOfBirth: "1988-02-14",
        sex: "female",
        memberId: "W123456789",
        payerName: "Aetna",
        phone: "(404) 555-0101",
        email: "avery.chen@example.com",
        address: "18 Peachtree Place",
        city: "Atlanta",
        state: "GA",
        postalCode: "30308",
        createdAt: "2026-09-02T09:00:00",
      },
      {
        id: "p2",
        firstName: "Jordan",
        lastName: "Blake",
        dateOfBirth: "1976-11-03",
        sex: "male",
        memberId: "CIG882211",
        payerName: "Cigna",
        phone: "(404) 555-0102",
        email: "jordan.blake@example.com",
        address: "440 West Paces",
        city: "Atlanta",
        state: "GA",
        postalCode: "30305",
        createdAt: "2026-09-04T09:00:00",
      },
      {
        id: "p3",
        firstName: "Samira",
        lastName: "Okonkwo",
        dateOfBirth: "1992-07-21",
        sex: "female",
        memberId: "BCBS44091",
        payerName: "Blue Cross Blue Shield",
        phone: "(404) 555-0103",
        email: "samira.okonkwo@example.com",
        address: "9 Decatur Street",
        city: "Decatur",
        state: "GA",
        postalCode: "30030",
        createdAt: "2026-09-06T09:00:00",
      },
      {
        id: "p4",
        firstName: "Luis",
        lastName: "Ortega",
        dateOfBirth: "1965-01-30",
        sex: "male",
        memberId: "HUM22910",
        payerName: "Humana",
        phone: "(404) 555-0104",
        email: "luis.ortega@example.com",
        address: "77 Memorial Drive",
        city: "Atlanta",
        state: "GA",
        postalCode: "30312",
        createdAt: "2026-09-08T09:00:00",
      },
      {
        id: "p5",
        firstName: "Priya",
        lastName: "Shah",
        dateOfBirth: "2001-05-09",
        sex: "female",
        memberId: "UHC100293",
        payerName: "UnitedHealthcare",
        phone: "(404) 555-0105",
        email: "priya.shah@example.com",
        address: "210 Highland Ave",
        city: "Atlanta",
        state: "GA",
        postalCode: "30307",
        createdAt: "2026-09-12T09:00:00",
      },
      {
        id: "p6",
        firstName: "Noah",
        lastName: "Bennett",
        dateOfBirth: "1954-09-12",
        sex: "male",
        memberId: "MCR445566",
        payerName: "Medicare",
        phone: "(404) 555-0106",
        email: "noah.bennett@example.com",
        address: "5 Clairmont Road",
        city: "Atlanta",
        state: "GA",
        postalCode: "30329",
        createdAt: "2026-09-15T09:00:00",
      },
    ],
    claims: [
      {
        id: "c1",
        patientId: "p1",
        payerName: "Aetna",
        dateOfService: "2026-09-18",
        status: "denied",
        controlNumber: "AET440192",
        placeOfService: "11",
        lines: [
          {
            id: "c1l1",
            cpt: "99214",
            description: "Office visit, moderate",
            modifier: "25",
            units: 1,
            charge: 210,
            icd: "M54.5",
          },
        ],
        denialReason: "Modifier does not match the procedure",
        carc: "4",
        rarc: "N519",
        source: "manual",
        createdAt: "2026-09-19T15:00:00",
        updatedAt: "2026-09-22T11:00:00",
      },
      {
        id: "c2",
        patientId: "p2",
        payerName: "Cigna",
        dateOfService: "2026-09-16",
        status: "denied",
        controlNumber: "CIG118273",
        placeOfService: "11",
        lines: [
          {
            id: "c2l1",
            cpt: "72148",
            description: "MRI lumbar spine",
            modifier: "",
            units: 1,
            charge: 890,
            icd: "M51.16",
          },
        ],
        denialReason: "Prior authorization was not on file",
        carc: "197",
        rarc: "N54",
        source: "manual",
        createdAt: "2026-09-17T12:00:00",
        updatedAt: "2026-09-21T09:30:00",
      },
      {
        id: "c3",
        patientId: "p3",
        payerName: "Blue Cross Blue Shield",
        dateOfService: "2026-09-24",
        status: "processing",
        controlNumber: "BCBS902811",
        placeOfService: "11",
        lines: [
          {
            id: "c3l1",
            cpt: "99213",
            description: "Office visit, low",
            modifier: "",
            units: 1,
            charge: 145,
            icd: "M54.2",
          },
        ],
        source: "manual",
        createdAt: "2026-09-24T16:10:00",
        updatedAt: "2026-09-25T08:00:00",
      },
      {
        id: "c4",
        patientId: "p4",
        payerName: "Humana",
        dateOfService: "2026-09-10",
        status: "paid",
        controlNumber: "HUM330194",
        placeOfService: "11",
        lines: [
          {
            id: "c4l1",
            cpt: "97110",
            description: "Therapeutic exercise",
            modifier: "GP",
            units: 2,
            charge: 78,
            icd: "M54.5",
          },
        ],
        source: "manual",
        createdAt: "2026-09-11T10:00:00",
        updatedAt: "2026-09-20T14:00:00",
      },
      {
        id: "c5",
        patientId: "p6",
        payerName: "Medicare",
        dateOfService: "2026-09-08",
        status: "accepted",
        controlNumber: "MCR220187",
        placeOfService: "11",
        lines: [
          {
            id: "c5l1",
            cpt: "99214",
            description: "Office visit, moderate",
            modifier: "",
            units: 1,
            charge: 198,
            icd: "M47.812",
          },
        ],
        source: "manual",
        createdAt: "2026-09-09T11:20:00",
        updatedAt: "2026-09-18T09:00:00",
      },
      {
        id: "c6",
        patientId: "p3",
        payerName: "Blue Cross Blue Shield",
        dateOfService: "2026-09-26",
        status: "submitted",
        controlNumber: "BCBS902944",
        placeOfService: "11",
        lines: [
          {
            id: "c6l1",
            cpt: "99213",
            description: "Office visit, low",
            modifier: "",
            units: 1,
            charge: 145,
            icd: "M54.2",
          },
        ],
        source: "manual",
        createdAt: "2026-09-26T13:00:00",
        updatedAt: "2026-09-26T13:00:00",
      },
      {
        id: "c7",
        patientId: "p5",
        payerName: "UnitedHealthcare",
        dateOfService: "2026-09-29",
        status: "draft",
        controlNumber: "AGT771203",
        placeOfService: "11",
        lines: [
          {
            id: "c7l1",
            cpt: "99214",
            description: "Office visit, moderate",
            modifier: "25",
            units: 1,
            charge: 210,
            icd: "M54.5",
          },
        ],
        agentNote: "Drafted from the visit note. Confirm the 25 modifier before submit.",
        source: "agent",
        createdAt: "2026-09-29T17:40:00",
        updatedAt: "2026-09-29T17:40:00",
      },
      {
        id: "c8",
        patientId: "p2",
        payerName: "Cigna",
        dateOfService: "2026-09-03",
        status: "rejected",
        controlNumber: "CIG118001",
        placeOfService: "11",
        lines: [
          {
            id: "c8l1",
            cpt: "99213",
            description: "Office visit, low",
            modifier: "",
            units: 1,
            charge: 145,
            icd: "M54.5",
          },
        ],
        denialReason: "Member id failed payer edits",
        carc: "16",
        rarc: "N290",
        source: "upload",
        createdAt: "2026-09-04T08:15:00",
        updatedAt: "2026-09-05T10:00:00",
      },
    ],
    appointments: [
      {
        id: "a1",
        patientId: "p1",
        providerName: "Elvis Francois, MD",
        start: "2026-09-30T09:30:00",
        durationMinutes: 30,
        reason: "Low back pain follow-up",
        status: "scheduled",
        notes: "",
      },
      {
        id: "a2",
        patientId: "p5",
        providerName: "Elvis Francois, MD",
        start: "2026-09-30T11:00:00",
        durationMinutes: 45,
        reason: "New neck pain",
        status: "scheduled",
        notes: "Bring imaging if available.",
      },
      {
        id: "a3",
        patientId: "p4",
        providerName: "Elvis Francois, MD",
        start: "2026-09-28T15:00:00",
        durationMinutes: 30,
        reason: "Post-therapy check",
        status: "completed",
        notes: "Exercise program continued.",
      },
      {
        id: "a4",
        patientId: "p6",
        providerName: "Elvis Francois, MD",
        start: "2026-10-02T10:15:00",
        durationMinutes: 30,
        reason: "Lumbar stenosis review",
        status: "scheduled",
        notes: "",
      },
      {
        id: "a5",
        patientId: "p3",
        providerName: "Elvis Francois, MD",
        start: "2026-10-03T13:45:00",
        durationMinutes: 20,
        reason: "Cervicalgia",
        status: "scheduled",
        notes: "",
      },
    ],
    eligibility: [
      {
        id: "e1",
        patientId: "p1",
        payerName: "Aetna",
        createdAt: "2026-09-29T08:30:00",
        active: true,
        copay: 40,
        coinsurance: 20,
        deductibleRemaining: 350,
        priorAuthRequired: false,
        summary: "Aetna shows active coverage. Office visit copay $40. Deductible remaining $350.",
      },
    ],
  };
}
