import { withChart } from "@/lib/rcm/chart";
import type { Appointment, ChartDocument, PatientInput, PracticeTask, RcmState } from "@/lib/rcm/types";

export const STORAGE_KEY = "alignment-practice-demo-v2";

const provider = "Elvis Francois, MD";

function docs(items: Array<[string, ChartDocument["status"], string?]>): ChartDocument[] {
  return items.map(([name, status, note]) => ({
    id: name.toLowerCase().replaceAll(" ", "-"),
    name,
    status,
    note: note ?? "",
  }));
}

function patient(
  id: string,
  createdAt: string,
  mrn: string,
  input: PatientInput,
  extra: Partial<ReturnType<typeof withChart>>,
) {
  return withChart(input, { ...extra, id, createdAt, mrn });
}

function visit(appointment: Appointment): Appointment {
  return appointment;
}

export function createSeedState(): RcmState {
  const patients = [
    patient(
      "p1",
      "2026-09-02T09:00:00",
      "100241",
      {
        firstName: "Avery",
        lastName: "Chen",
        dateOfBirth: "1988-02-14",
        sex: "female",
        memberId: "W123456789",
        payerName: "Aetna",
        phone: "(404) 555-0101",
        email: "avery.chen@example.com",
        address: "18 Peachtree Place",
        city: "Atlanta",
        state: "GA",
        postalCode: "30308",
      },
      {
        preferredName: "Avery",
        pronouns: "she/her",
        language: "English",
        preferredContact: "text",
        emergencyName: "Mei Chen",
        emergencyPhone: "(404) 555-0191",
        emergencyRelation: "Spouse",
        guarantorName: "Avery Chen",
        guarantorRelation: "self",
        guarantorPhone: "(404) 555-0101",
        pcpName: "Helen Cho, MD",
        pcpPhone: "(404) 555-0170",
        referringName: "Helen Cho, MD",
        referringPhone: "(404) 555-0170",
        pharmacyName: "Midtown Pharmacy",
        pharmacyPhone: "(404) 555-0160",
        portalStatus: "active",
        allergiesReviewed: true,
        medicalHistory: "Low back pain for two years. No diabetes. No anticoagulant use.",
        surgicalHistory: "None.",
        flags: [],
        coverages: [
          {
            id: "p1-primary",
            rank: "primary",
            payerName: "Aetna",
            planName: "Aetna Choice PPO",
            memberId: "W123456789",
            groupNumber: "884120",
            subscriberName: "Avery Chen",
            relationship: "self",
            effectiveDate: "2026-01-01",
            copay: 40,
          },
        ],
        problems: [
          { id: "p1-pr1", name: "Low back pain", icd: "M54.5", status: "active", onset: "2024-06-01" },
          { id: "p1-pr2", name: "Lumbar disc displacement", icd: "M51.26", status: "active", onset: "2026-08-12" },
        ],
        allergies: [{ id: "p1-al1", substance: "Sulfa", reaction: "Rash", severity: "moderate" }],
        medications: [
          { id: "p1-med1", name: "Ibuprofen", dose: "600 mg", frequency: "As needed", status: "active" },
          { id: "p1-med2", name: "Cyclobenzaprine", dose: "5 mg", frequency: "At night", status: "active" },
        ],
        documents: docs([
          ["Photo ID", "received"],
          ["Insurance card", "received"],
          ["Consent to treat", "signed"],
          ["New patient intake", "signed"],
          ["Privacy acknowledgment", "signed"],
          ["Outside records", "received", "Lumbar MRI from August"],
        ]),
      },
    ),
    patient(
      "p2",
      "2026-09-04T09:00:00",
      "100258",
      {
        firstName: "Jordan",
        lastName: "Blake",
        dateOfBirth: "1976-11-03",
        sex: "male",
        memberId: "CIG882211",
        payerName: "Cigna",
        phone: "(404) 555-0102",
        email: "jordan.blake@example.com",
        address: "440 West Paces",
        city: "Atlanta",
        state: "GA",
        postalCode: "30305",
      },
      {
        preferredName: "Jordan",
        pronouns: "he/him",
        language: "English",
        preferredContact: "phone",
        emergencyName: "Chris Blake",
        emergencyPhone: "(404) 555-0192",
        emergencyRelation: "Sibling",
        guarantorName: "Jordan Blake",
        guarantorRelation: "self",
        guarantorPhone: "(404) 555-0102",
        pcpName: "Marcus Hale, MD",
        pcpPhone: "(404) 555-0172",
        referringName: "Marcus Hale, MD",
        referringPhone: "(404) 555-0172",
        pharmacyName: "Buckhead Pharmacy",
        pharmacyPhone: "(404) 555-0162",
        portalStatus: "invited",
        allergiesReviewed: true,
        medicalHistory: "Lumbar radiculopathy. Hypertension, on lisinopril.",
        surgicalHistory: "None.",
        flags: ["Imaging authorization pending"],
        coverages: [
          {
            id: "p2-primary",
            rank: "primary",
            payerName: "Cigna",
            planName: "Cigna Open Access",
            memberId: "CIG882211",
            groupNumber: "22019",
            subscriberName: "Jordan Blake",
            relationship: "self",
            effectiveDate: "2025-07-01",
            copay: 50,
          },
        ],
        problems: [
          { id: "p2-pr1", name: "Lumbar radiculopathy", icd: "M54.16", status: "active", onset: "2026-07-20" },
          { id: "p2-pr2", name: "Essential hypertension", icd: "I10", status: "active", onset: "2018-03-01" },
        ],
        allergies: [],
        medications: [{ id: "p2-med1", name: "Lisinopril", dose: "10 mg", frequency: "Daily", status: "active" }],
        documents: docs([
          ["Photo ID", "received"],
          ["Insurance card", "received"],
          ["Consent to treat", "signed"],
          ["New patient intake", "signed"],
          ["Privacy acknowledgment", "signed"],
          ["Outside records", "missing", "Lumbar MRI report not in the chart"],
        ]),
      },
    ),
    patient(
      "p3",
      "2026-09-06T09:00:00",
      "100263",
      {
        firstName: "Samira",
        lastName: "Okonkwo",
        dateOfBirth: "1992-07-21",
        sex: "female",
        memberId: "BCBS44091",
        payerName: "Blue Cross Blue Shield",
        phone: "(404) 555-0103",
        email: "samira.okonkwo@example.com",
        address: "9 Decatur Street",
        city: "Decatur",
        state: "GA",
        postalCode: "30030",
      },
      {
        preferredName: "Samira",
        pronouns: "she/her",
        language: "English",
        preferredContact: "email",
        emergencyName: "Tunde Okonkwo",
        emergencyPhone: "(404) 555-0193",
        emergencyRelation: "Spouse",
        guarantorName: "Samira Okonkwo",
        guarantorRelation: "self",
        guarantorPhone: "(404) 555-0103",
        pcpName: "Lena Ortiz, DO",
        pcpPhone: "(404) 555-0174",
        referringName: "Lena Ortiz, DO",
        referringPhone: "(404) 555-0174",
        pharmacyName: "Decatur Pharmacy",
        pharmacyPhone: "(404) 555-0164",
        portalStatus: "active",
        allergiesReviewed: true,
        medicalHistory: "Neck pain after a long drive. No prior spine surgery.",
        surgicalHistory: "None.",
        flags: ["No-show yesterday"],
        coverages: [
          {
            id: "p3-primary",
            rank: "primary",
            payerName: "Blue Cross Blue Shield",
            planName: "BCBS PPO",
            memberId: "BCBS44091",
            groupNumber: "GA440",
            subscriberName: "Samira Okonkwo",
            relationship: "self",
            effectiveDate: "2026-01-01",
            copay: 35,
          },
        ],
        problems: [{ id: "p3-pr1", name: "Cervicalgia", icd: "M54.2", status: "active", onset: "2026-09-01" }],
        allergies: [{ id: "p3-al1", substance: "Penicillin", reaction: "Hives", severity: "severe" }],
        medications: [],
        documents: docs([
          ["Photo ID", "received"],
          ["Insurance card", "received"],
          ["Consent to treat", "signed"],
          ["New patient intake", "signed"],
          ["Privacy acknowledgment", "signed"],
          ["Outside records", "missing"],
        ]),
      },
    ),
    patient(
      "p4",
      "2026-09-08T09:00:00",
      "100277",
      {
        firstName: "Luis",
        lastName: "Ortega",
        dateOfBirth: "1965-01-30",
        sex: "male",
        memberId: "HUM22910",
        payerName: "Humana",
        phone: "(404) 555-0104",
        email: "luis.ortega@example.com",
        address: "77 Memorial Drive",
        city: "Atlanta",
        state: "GA",
        postalCode: "30312",
      },
      {
        preferredName: "Luis",
        pronouns: "he/him",
        language: "Spanish",
        preferredContact: "phone",
        emergencyName: "Rosa Ortega",
        emergencyPhone: "(404) 555-0194",
        emergencyRelation: "Spouse",
        guarantorName: "Luis Ortega",
        guarantorRelation: "self",
        guarantorPhone: "(404) 555-0104",
        pcpName: "Anita Shah, MD",
        pcpPhone: "(404) 555-0176",
        referringName: "Anita Shah, MD",
        referringPhone: "(404) 555-0176",
        pharmacyName: "Grant Park Pharmacy",
        pharmacyPhone: "(404) 555-0166",
        portalStatus: "none",
        allergiesReviewed: true,
        medicalHistory: "Lumbar stenosis. Finished a course of therapy.",
        surgicalHistory: "Right knee arthroscopy, 2019.",
        flags: ["Interpreter needed"],
        coverages: [
          {
            id: "p4-primary",
            rank: "primary",
            payerName: "Humana",
            planName: "Humana Gold",
            memberId: "HUM22910",
            groupNumber: "H229",
            subscriberName: "Luis Ortega",
            relationship: "self",
            effectiveDate: "2026-01-01",
            copay: 25,
          },
          {
            id: "p4-secondary",
            rank: "secondary",
            payerName: "Medicare",
            planName: "Medicare Part B",
            memberId: "1EG4-TE5-MK72",
            groupNumber: "",
            subscriberName: "Luis Ortega",
            relationship: "self",
            effectiveDate: "2026-02-01",
            copay: 0,
          },
        ],
        problems: [{ id: "p4-pr1", name: "Spinal stenosis, lumbar", icd: "M48.06", status: "active", onset: "2025-11-01" }],
        allergies: [],
        medications: [{ id: "p4-med1", name: "Acetaminophen", dose: "500 mg", frequency: "As needed", status: "active" }],
        documents: docs([
          ["Photo ID", "received"],
          ["Insurance card", "received"],
          ["Consent to treat", "signed"],
          ["New patient intake", "signed"],
          ["Privacy acknowledgment", "signed"],
          ["Outside records", "received", "Therapy notes"],
        ]),
      },
    ),
    patient(
      "p5",
      "2026-09-12T09:00:00",
      "100284",
      {
        firstName: "Priya",
        lastName: "Shah",
        dateOfBirth: "2001-05-09",
        sex: "female",
        memberId: "UHC100293",
        payerName: "UnitedHealthcare",
        phone: "(404) 555-0105",
        email: "priya.shah@example.com",
        address: "210 Highland Ave",
        city: "Atlanta",
        state: "GA",
        postalCode: "30307",
      },
      {
        preferredName: "Priya",
        pronouns: "she/her",
        language: "English",
        preferredContact: "text",
        emergencyName: "Anika Shah",
        emergencyPhone: "(404) 555-0195",
        emergencyRelation: "Parent",
        guarantorName: "Anika Shah",
        guarantorRelation: "parent",
        guarantorPhone: "(404) 555-0195",
        pcpName: "",
        pcpPhone: "",
        referringName: "",
        referringPhone: "",
        pharmacyName: "",
        pharmacyPhone: "",
        portalStatus: "invited",
        allergiesReviewed: false,
        medicalHistory: "",
        surgicalHistory: "",
        flags: ["New patient"],
        coverages: [
          {
            id: "p5-primary",
            rank: "primary",
            payerName: "UnitedHealthcare",
            planName: "UHC Choice Plus",
            memberId: "UHC100293",
            groupNumber: "",
            subscriberName: "Anika Shah",
            relationship: "child",
            effectiveDate: "2026-01-01",
            copay: 45,
          },
        ],
        problems: [],
        allergies: [],
        medications: [],
        documents: docs([
          ["Photo ID", "missing"],
          ["Insurance card", "missing"],
          ["Consent to treat", "missing"],
          ["New patient intake", "missing"],
          ["Privacy acknowledgment", "missing"],
          ["Outside records", "missing"],
        ]),
      },
    ),
    patient(
      "p6",
      "2026-09-15T09:00:00",
      "100291",
      {
        firstName: "Noah",
        lastName: "Bennett",
        dateOfBirth: "1954-09-12",
        sex: "male",
        memberId: "MCR445566",
        payerName: "Medicare",
        phone: "(404) 555-0106",
        email: "noah.bennett@example.com",
        address: "5 Clairmont Road",
        city: "Atlanta",
        state: "GA",
        postalCode: "30329",
      },
      {
        preferredName: "Noah",
        pronouns: "he/him",
        language: "English",
        preferredContact: "phone",
        emergencyName: "Claire Bennett",
        emergencyPhone: "(404) 555-0196",
        emergencyRelation: "Daughter",
        guarantorName: "Noah Bennett",
        guarantorRelation: "self",
        guarantorPhone: "(404) 555-0106",
        pcpName: "Owen Briggs, MD",
        pcpPhone: "(404) 555-0178",
        referringName: "Owen Briggs, MD",
        referringPhone: "(404) 555-0178",
        pharmacyName: "Clairmont Pharmacy",
        pharmacyPhone: "(404) 555-0168",
        portalStatus: "none",
        allergiesReviewed: true,
        medicalHistory: "Lumbar stenosis. Uses a cane on longer walks. No anticoagulant.",
        surgicalHistory: "None.",
        flags: ["Fall risk", "Needs extra time"],
        coverages: [
          {
            id: "p6-primary",
            rank: "primary",
            payerName: "Medicare",
            planName: "Medicare Part B",
            memberId: "MCR445566",
            groupNumber: "",
            subscriberName: "Noah Bennett",
            relationship: "self",
            effectiveDate: "2019-09-01",
            copay: 0,
          },
        ],
        problems: [{ id: "p6-pr1", name: "Spinal stenosis, lumbar", icd: "M48.06", status: "active", onset: "2023-04-01" }],
        allergies: [{ id: "p6-al1", substance: "Codeine", reaction: "Nausea", severity: "mild" }],
        medications: [{ id: "p6-med1", name: "Acetaminophen", dose: "650 mg", frequency: "Three times daily", status: "active" }],
        documents: docs([
          ["Photo ID", "received"],
          ["Insurance card", "received"],
          ["Consent to treat", "signed"],
          ["New patient intake", "signed"],
          ["Privacy acknowledgment", "signed"],
          ["Outside records", "received"],
        ]),
      },
    ),
  ];

  const appointments: Appointment[] = [
    visit({
      id: "a-yesterday",
      patientId: "p3",
      providerName: provider,
      start: "2026-09-29T14:00:00",
      durationMinutes: 20,
      reason: "Cervicalgia",
      status: "no_show",
      notes: "Did not arrive. Front desk left a voicemail.",
      visitType: "follow_up",
      room: "Room 1",
      confirmation: "left_message",
      chiefComplaint: "Neck pain",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "", heartRate: "", weightLb: "", painScore: "" },
      copayCollected: null,
    }),
    visit({
      id: "a-noah",
      patientId: "p6",
      providerName: provider,
      start: "2026-09-30T08:15:00",
      durationMinutes: 30,
      reason: "Lumbar stenosis review",
      status: "completed",
      notes: "Daughter accompanied. Cane used from the waiting room.",
      visitType: "follow_up",
      room: "Room 1",
      confirmation: "confirmed",
      chiefComplaint: "Leg heaviness after walking two blocks.",
      assessment: "Stable lumbar stenosis. No red-flag weakness.",
      plan: "Continue home program. Return in two weeks. Extra time at check-in.",
      vitals: { bloodPressure: "138/76", heartRate: "72", weightLb: "182", painScore: "4" },
      copayCollected: 0,
    }),
    visit({
      id: "a-avery",
      patientId: "p1",
      providerName: provider,
      start: "2026-09-30T09:30:00",
      durationMinutes: 30,
      reason: "Low back pain follow-up",
      status: "in_progress",
      notes: "Checked in. Copay still due at the desk.",
      visitType: "follow_up",
      room: "Room 2",
      confirmation: "confirmed",
      chiefComplaint: "Low back pain, worse with sitting.",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "122/78", heartRate: "68", weightLb: "146", painScore: "5" },
      copayCollected: null,
    }),
    visit({
      id: "a-priya",
      patientId: "p5",
      providerName: provider,
      start: "2026-09-30T11:00:00",
      durationMinutes: 45,
      reason: "New neck pain",
      status: "scheduled",
      notes: "Intake packet was sent and has not come back.",
      visitType: "new",
      room: "Room 1",
      confirmation: "unconfirmed",
      chiefComplaint: "",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "", heartRate: "", weightLb: "", painScore: "" },
      copayCollected: null,
    }),
    visit({
      id: "a-luis",
      patientId: "p4",
      providerName: provider,
      start: "2026-09-30T13:15:00",
      durationMinutes: 30,
      reason: "Post-therapy check",
      status: "arrived",
      notes: "Spanish interpreter requested.",
      visitType: "follow_up",
      room: "Room 2",
      confirmation: "confirmed",
      chiefComplaint: "Stiffness after therapy.",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "", heartRate: "", weightLb: "", painScore: "" },
      copayCollected: null,
    }),
    visit({
      id: "a-jordan",
      patientId: "p2",
      providerName: provider,
      start: "2026-09-30T14:30:00",
      durationMinutes: 30,
      reason: "MRI review",
      status: "scheduled",
      notes: "Report is not in the chart yet.",
      visitType: "imaging_review",
      room: "Room 1",
      confirmation: "confirmed",
      chiefComplaint: "Right leg pain.",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "", heartRate: "", weightLb: "", painScore: "" },
      copayCollected: null,
    }),
    visit({
      id: "a-samira",
      patientId: "p3",
      providerName: provider,
      start: "2026-09-30T16:00:00",
      durationMinutes: 20,
      reason: "Neck pain, rescheduled",
      status: "scheduled",
      notes: "No-show yesterday. Needs a confirmation call.",
      visitType: "follow_up",
      room: "Room 1",
      confirmation: "unconfirmed",
      chiefComplaint: "Neck pain",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "", heartRate: "", weightLb: "", painScore: "" },
      copayCollected: null,
    }),
    visit({
      id: "a-tomorrow-avery",
      patientId: "p1",
      providerName: provider,
      start: "2026-10-01T10:00:00",
      durationMinutes: 20,
      reason: "Exercise check",
      status: "scheduled",
      notes: "",
      visitType: "follow_up",
      room: "Room 2",
      confirmation: "confirmed",
      chiefComplaint: "",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "", heartRate: "", weightLb: "", painScore: "" },
      copayCollected: null,
    }),
    visit({
      id: "a-friday-noah",
      patientId: "p6",
      providerName: provider,
      start: "2026-10-02T10:15:00",
      durationMinutes: 30,
      reason: "Stenosis follow-up",
      status: "scheduled",
      notes: "Book a longer slot.",
      visitType: "follow_up",
      room: "Room 1",
      confirmation: "confirmed",
      chiefComplaint: "",
      assessment: "",
      plan: "",
      vitals: { bloodPressure: "", heartRate: "", weightLb: "", painScore: "" },
      copayCollected: null,
    }),
    visit({
      id: "a-past-luis",
      patientId: "p4",
      providerName: provider,
      start: "2026-09-16T15:00:00",
      durationMinutes: 30,
      reason: "Therapy progress",
      status: "completed",
      notes: "Interpreter present.",
      visitType: "follow_up",
      room: "Room 2",
      confirmation: "confirmed",
      chiefComplaint: "Walking tolerance improving.",
      assessment: "Therapy is helping. Continue the program.",
      plan: "Return after the last therapy week.",
      vitals: { bloodPressure: "128/74", heartRate: "70", weightLb: "190", painScore: "3" },
      copayCollected: 25,
    }),
  ];

  const tasks: PracticeTask[] = [
    {
      id: "t1",
      patientId: "p5",
      title: "Confirm Priya Shah and collect intake",
      detail: "11:00 new patient. Packet, photo ID, and insurance card are still missing.",
      due: "2026-09-30",
      status: "open",
    },
    {
      id: "t2",
      patientId: "p1",
      title: "Collect Avery Chen's copay",
      detail: "Aetna copay is $40. She is in Room 2.",
      due: "2026-09-30",
      status: "open",
    },
    {
      id: "t3",
      patientId: "p2",
      title: "Get Jordan Blake's MRI report",
      detail: "Imaging review is at 2:30 and the outside report is not in the chart.",
      due: "2026-09-30",
      status: "open",
    },
    {
      id: "t4",
      patientId: "p3",
      title: "Call Samira Okonkwo to confirm 4:00",
      detail: "She no-showed yesterday. Penicillin allergy is on the chart.",
      due: "2026-09-30",
      status: "open",
    },
    {
      id: "t5",
      patientId: "p4",
      title: "Interpreter for Luis Ortega",
      detail: "Spanish interpreter requested. He has arrived.",
      due: "2026-09-30",
      status: "open",
    },
    {
      id: "t6",
      patientId: "p6",
      title: "Note extra time for Noah Bennett",
      detail: "Fall risk. Daughter is the emergency contact. Next visit is Friday.",
      due: "2026-10-02",
      status: "open",
    },
  ];

  return {
    practice: {
      legalName: "The Alignment Clinic",
      physicianName: provider,
      npi: "1999999984",
      taxId: "00-0000000",
      taxonomy: "207X00000X",
      phone: "(404) 555-0148",
      address: "Atlanta, GA",
      posCode: "11",
    },
    patients,
    appointments,
    tasks,
    claims: [
      {
        id: "c1",
        patientId: "p1",
        payerName: "Aetna",
        dateOfService: "2026-09-18",
        status: "denied",
        controlNumber: "AET440192",
        placeOfService: "11",
        lines: [
          {
            id: "c1l1",
            cpt: "99214",
            description: "Office visit, moderate",
            modifier: "25",
            units: 1,
            charge: 210,
            icd: "M54.5",
          },
        ],
        denialReason: "Modifier does not match the procedure",
        carc: "4",
        rarc: "N519",
        source: "manual",
        createdAt: "2026-09-19T15:00:00",
        updatedAt: "2026-09-22T11:00:00",
      },
      {
        id: "c2",
        patientId: "p2",
        payerName: "Cigna",
        dateOfService: "2026-09-16",
        status: "denied",
        controlNumber: "CIG118273",
        placeOfService: "11",
        lines: [
          {
            id: "c2l1",
            cpt: "72148",
            description: "MRI lumbar spine",
            modifier: "",
            units: 1,
            charge: 890,
            icd: "M51.16",
          },
        ],
        denialReason: "Prior authorization was not on file",
        carc: "197",
        rarc: "N54",
        source: "manual",
        createdAt: "2026-09-17T12:00:00",
        updatedAt: "2026-09-21T09:30:00",
      },
      {
        id: "c3",
        patientId: "p3",
        payerName: "Blue Cross Blue Shield",
        dateOfService: "2026-09-24",
        status: "processing",
        controlNumber: "BCBS902811",
        placeOfService: "11",
        lines: [
          {
            id: "c3l1",
            cpt: "99213",
            description: "Office visit, low",
            modifier: "",
            units: 1,
            charge: 145,
            icd: "M54.2",
          },
        ],
        source: "manual",
        createdAt: "2026-09-24T16:10:00",
        updatedAt: "2026-09-25T08:00:00",
      },
      {
        id: "c4",
        patientId: "p4",
        payerName: "Humana",
        dateOfService: "2026-09-10",
        status: "paid",
        controlNumber: "HUM330194",
        placeOfService: "11",
        lines: [
          {
            id: "c4l1",
            cpt: "97110",
            description: "Therapeutic exercise",
            modifier: "GP",
            units: 2,
            charge: 78,
            icd: "M54.5",
          },
        ],
        source: "manual",
        createdAt: "2026-09-11T10:00:00",
        updatedAt: "2026-09-20T14:00:00",
      },
      {
        id: "c5",
        patientId: "p6",
        payerName: "Medicare",
        dateOfService: "2026-09-08",
        status: "accepted",
        controlNumber: "MCR220187",
        placeOfService: "11",
        lines: [
          {
            id: "c5l1",
            cpt: "99214",
            description: "Office visit, moderate",
            modifier: "",
            units: 1,
            charge: 198,
            icd: "M47.812",
          },
        ],
        source: "manual",
        createdAt: "2026-09-09T11:20:00",
        updatedAt: "2026-09-18T09:00:00",
      },
      {
        id: "c6",
        patientId: "p3",
        payerName: "Blue Cross Blue Shield",
        dateOfService: "2026-09-26",
        status: "submitted",
        controlNumber: "BCBS902944",
        placeOfService: "11",
        lines: [
          {
            id: "c6l1",
            cpt: "99213",
            description: "Office visit, low",
            modifier: "",
            units: 1,
            charge: 145,
            icd: "M54.2",
          },
        ],
        source: "manual",
        createdAt: "2026-09-26T13:00:00",
        updatedAt: "2026-09-26T13:00:00",
      },
      {
        id: "c7",
        patientId: "p5",
        payerName: "UnitedHealthcare",
        dateOfService: "2026-09-29",
        status: "draft",
        controlNumber: "AGT771203",
        placeOfService: "11",
        lines: [
          {
            id: "c7l1",
            cpt: "99214",
            description: "Office visit, moderate",
            modifier: "25",
            units: 1,
            charge: 210,
            icd: "M54.5",
          },
        ],
        agentNote: "Drafted from the visit note. Confirm the 25 modifier before submit.",
        source: "agent",
        createdAt: "2026-09-29T17:40:00",
        updatedAt: "2026-09-29T17:40:00",
      },
      {
        id: "c8",
        patientId: "p2",
        payerName: "Cigna",
        dateOfService: "2026-09-03",
        status: "rejected",
        controlNumber: "CIG118001",
        placeOfService: "11",
        lines: [
          {
            id: "c8l1",
            cpt: "99213",
            description: "Office visit, low",
            modifier: "",
            units: 1,
            charge: 145,
            icd: "M54.5",
          },
        ],
        denialReason: "Member id failed payer edits",
        carc: "16",
        rarc: "N290",
        source: "upload",
        createdAt: "2026-09-04T08:15:00",
        updatedAt: "2026-09-05T10:00:00",
      },
    ],
    eligibility: [
      {
        id: "e1",
        patientId: "p1",
        payerName: "Aetna",
        createdAt: "2026-09-29T08:30:00",
        active: true,
        copay: 40,
        coinsurance: 20,
        deductibleRemaining: 350,
        priorAuthRequired: false,
        summary: "Aetna shows active coverage. Office visit copay $40. Deductible remaining $350.",
      },
    ],
  };
}
